# Generated by Django 5.2.7 on 2025-10-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tel_number',
            new_name='tel',
        ),
    ]
