# Generated by Django 5.2.7 on 2025-10-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='features',
            field=models.TextField(help_text='List of features'),
        ),
    ]
